### ISSUE TITLE
UUID-indexed map doesn't transact

### ISSUE THREAD

**Issue by bobby** [smothers/cause#8]
I'm unable to add a map with UUID keys.  Reproducing case:

``` clojure
(cause/transact (cause/base) [[nil nil {#uuid "79f12947-b05b-4b57-8a19-1f4ef587a08a" {:id #uuid "79f12947-b05b-4b57-8a19-1f4ef587a08a"}}]])
```

Error Message (CLJS):

```
Error: The cause of this node is not in the tree.
    at new cljs$core$ExceptionInfo (http://localhost:8000/js/compiled/cljs-runtime/cljs.core.js:37198:10)
    at Function.cljs$core$IFn$_invoke$arity$3 (http://localhost:8000/js/compiled/cljs-runtime/cljs.core.js:37259:9)
    at Function.cljs$core$IFn$_invoke$arity$2 (http://localhost:8000/js/compiled/cljs-runtime/cljs.core.js:37255:26)
    at Function.cljs$core$IFn$_invoke$arity$4 (http://localhost:8000/js/compiled/cljs-runtime/causal.collections.shared.js:292:25)
    at Object.causal$protocols$CausalTree$insert$arity$3 (http://localhost:8000/js/compiled/cljs-runtime/causal.collections.map.js:544:79)
    at Function.cljs$core$IFn$_invoke$arity$3 (http://localhost:8000/js/compiled/cljs-runtime/causal.protocols.js:168:19)
    at http://localhost:8000/js/compiled/cljs-runtime/causal.base.core.js:191:32
    at http://localhost:8000/js/compiled/cljs-runtime/cljs.core.js:19649:89
    at Function.cljs$core$IFn$_invoke$arity$3 (http://localhost:8000/js/compiled/cljs-runtime/cljs.core.js:19650:3)
    at Function.cljs$core$IFn$_invoke$arity$3 (http://localhost:8000/js/compiled/cljs-runtime/cljs.core.js:19646:78)[:app] Compiling ..
```

**Comment by smothers** [comment]
#9
